##### Consider the below code to answer further questions:


import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)


##### Q1. Is there any difference in the data type of  list_ and array_list? If there is then write a code to print the data types of both the variables.

In [1]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

###### Ans-  Yes there  is difference between data type  of  list_ and array_list because list_ is a list datatype and array_list is a unsigned integer of 8-bit.

In [2]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [3]:
array_list.dtype


dtype('<U1')

In [4]:
print(type(list_))

<class 'list'>


##### Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [5]:
arr=np.array(list_)
print(arr.dtype)


# or we can print the type every element inside the list

for item in list_:
    print(type(item))

<U1
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [6]:
print(type(list_))

<class 'list'>


In [7]:
array_list.dtype

dtype('<U1')

In [8]:
print(type(array_list))

<class 'numpy.ndarray'>



##### Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and array_list.

##### Ans-  Yes there  will be a  difference between data type  of  list_ and array_list if we print the data type of both the variables, then we get  list_ is a list datatype and array_list is a ndarray(N- dimensional).

In [9]:
array_list = np.array(object = list_, dtype = int)


In [10]:
print(type(list_))

<class 'list'>


In [11]:
print(type(array_list))

<class 'numpy.ndarray'>


import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
##### Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape

(ii) size

In [12]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
num_array.shape


(2, 3)

In [14]:
num_array.size

6

##### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function

In [15]:
arr=np.zeros([3,3],dtype=int)
arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

##### Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [16]:
identity_matrix=np.identity(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
